name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }]  # Every Sunday at midnight UTC
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          config_theme: calm
          config_contributions: public
          config_timezone: America/New_York

          # Core sections
          base: header, activity, community, repositories, metadata

          # Cool Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%

          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_limit: 15

          plugin_repositories: yes
          plugin_isocalendar: yes

          plugin_activity: no
