name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }]  # Every Sunday at midnight UTC
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          
          config_theme: rose_pine
          # Core sections
          base: header, activity, community, repositories, metadata

          # Cool Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%
          
          plugin_topics: yes
          plugin_topics_mode: starred  # Shows only topics from starred repos
          plugin_topics_limit: 15      # You can adjust from 0–100

          plugin_repositories: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: beginner


          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
