name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ananyadas2607
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Generate Snake (Dark mode)
        uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: ananyadas2607
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: '#46a9fc'
          color_dots: '#24292e,#046064,#046064,#00889c,#46a9fc'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
